# Generated by Django 3.1.1 on 2020-09-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('logo', models.CharField(max_length=200)),
                ('record', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], unique=True)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
