# Generated by Django 3.1.1 on 2020-09-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='box_score',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
