# Generated by Django 3.1.1 on 2020-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_rankings', '0004_auto_20200917_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRankWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_week', models.IntegerField()),
            ],
        ),
    ]
